swagger:
  enable: true

#spring:
#  security:
#    user:
#      name: admin
#      password: admin
spring:
  datasource:
    url: jdbc:h2:mem:JWTDEMO;DB_CLOSE_DELAY=-1;MODE=MYSQL
jwt:
  secret: "secret"